config/routes.rb
Rails.application.routes.draw do


  resources :sent_emails
  resources :credit_payments
  root :to => 'dashboards#index'
  devise_for :users
  resources :projects
  resources :salaries
  resources :freelances
  resources :invoices
  resources :clients

  resources :payments do
      collection do
        get 'enter_payment'
        put 'update_individual_payment'
        get 'filter_payments'
        get 'bulk_actions'
        get 'undo_actions'
        get 'payments_history'
        get 'invoice_payments_history'
        post 'delete_non_credit_payments'
      end
    end

    resources :invoices do
      
      collection do
        get 'filter_invoices'
        get 'bulk_actions'
        get 'undo_actions'
        post 'duplicate_invoice'
        get 'enter_single_payment'
        get 'send_invoice'
        post 'paypal_payments'
        get  'paypal_payments'
        post 'preview'
        get 'preview'
        get 'credit_card_info'
        get 'selected_currency'
      end
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/credit_payment.rb
class CreditPayment < ApplicationRecord
  belongs_to :payment
  belongs_to :invoice
  # callbacks
    after_destroy :update_credit_applied

    def update_credit_applied
        payment.update_attributes(:credit_applied => payment.credit_applied - amount) if payment.present?
    end
  end

app/controllers/credit_payments_controller.rb
class CreditPaymentsController < ApplicationController
  before_action :set_credit_payment, only: [:show, :edit, :update, :destroy]

  # GET /credit_payments
  # GET /credit_payments.json
  def index
    @credit_payments = CreditPayment.all
  end

  # GET /credit_payments/1
  # GET /credit_payments/1.json
  def show
  end

  # GET /credit_payments/new
  def new
    @credit_payment = CreditPayment.new
  end

  # GET /credit_payments/1/edit
  def edit
  end

  # POST /credit_payments
  # POST /credit_payments.json
  def create
    @credit_payment = CreditPayment.new(credit_payment_params)

    respond_to do |format|
      if @credit_payment.save
        format.html { redirect_to @credit_payment, notice: 'Credit payment was successfully created.' }
        format.json { render :show, status: :created, location: @credit_payment }
      else
        format.html { render :new }
        format.json { render json: @credit_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_payments/1
  # PATCH/PUT /credit_payments/1.json
  def update
    respond_to do |format|
      if @credit_payment.update(credit_payment_params)
        format.html { redirect_to @credit_payment, notice: 'Credit payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_payment }
      else
        format.html { render :edit }
        format.json { render json: @credit_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_payments/1
  # DELETE /credit_payments/1.json
  def destroy
    @credit_payment.destroy
    respond_to do |format|
      format.html { redirect_to credit_payments_url, notice: 'Credit payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_payment
      @credit_payment = CreditPayment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_payment_params
      params.require(:credit_payment).permit(:amount, :payment_id, :invoice_id)
    end
end

app/helpers/credit_payments_helper.rb
module CreditPaymentsHelper
end

app/views/credit_payments/_form.html.erb
<%= form_with(model: credit_payment, local: true) do |form| %>
  <% if credit_payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(credit_payment.errors.count, "error") %> prohibited this credit_payment from being saved:</h2>

      <ul>
      <% credit_payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :credit_payment_amount %>
  </div>

  <div class="field">
    <%= form.label :payment_id %>
    <%= form.text_field :payment_id, id: :credit_payment_payment_id %>
  </div>

  <div class="field">
    <%= form.label :invoice_id %>
    <%= form.text_field :invoice_id, id: :credit_payment_invoice_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/credit_payments/edit.html.erb
<h1>Editing Credit Payment</h1>

<%= render 'form', credit_payment: @credit_payment %>

<%= link_to 'Show', @credit_payment %> |
<%= link_to 'Back', credit_payments_path %>

app/views/credit_payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Credit Payments</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Payment</th>
      <th>Invoice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_payments.each do |credit_payment| %>
      <tr>
        <td><%= credit_payment.amount %></td>
        <td><%= credit_payment.payment %></td>
        <td><%= credit_payment.invoice %></td>
        <td><%= link_to 'Show', credit_payment %></td>
        <td><%= link_to 'Edit', edit_credit_payment_path(credit_payment) %></td>
        <td><%= link_to 'Destroy', credit_payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit Payment', new_credit_payment_path %>

app/views/credit_payments/new.html.erb
<h1>New Credit Payment</h1>

<%= render 'form', credit_payment: @credit_payment %>

<%= link_to 'Back', credit_payments_path %>

app/views/credit_payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @credit_payment.amount %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @credit_payment.payment %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @credit_payment.invoice %>
</p>

<%= link_to 'Edit', edit_credit_payment_path(@credit_payment) %> |
<%= link_to 'Back', credit_payments_path %>