config/routes.rb
Rails.application.routes.draw do


  resources :sent_emails
  resources :credit_payments
  root :to => 'dashboards#index'
  devise_for :users
  resources :projects
  resources :salaries
  resources :freelances
  resources :invoices
  resources :clients

  resources :payments do
      collection do
        get 'enter_payment'
        put 'update_individual_payment'
        get 'filter_payments'
        get 'bulk_actions'
        get 'undo_actions'
        get 'payments_history'
        get 'invoice_payments_history'
        post 'delete_non_credit_payments'
      end
    end

    resources :invoices do
      
      collection do
        get 'filter_invoices'
        get 'bulk_actions'
        get 'undo_actions'
        post 'duplicate_invoice'
        get 'enter_single_payment'
        get 'send_invoice'
        post 'paypal_payments'
        get  'paypal_payments'
        post 'preview'
        get 'preview'
        get 'credit_card_info'
        get 'selected_currency'
      end
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :client
  belongs_to :freelance
  has_one :invoice
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = Project.where(:project_delete=>'0')
  end

  def show
    @project  = Project.find(params[:id])
  end

  def new
    @project = Project.new
    @client = Client.all
    @freelance = Freelance.where(:freelance_delete=>'0')
  end

  def create
    @project = Project.new(params.require(:project).permit(:client_id, :ifreelance_id, :delivery_date, :project_amount, :project_paid, :project_status, :project_details))

    if @project.save
      Invoice.create(:project_id=>Project.last.id)
      redirect_to edit_invoice_path(Project.last.id), :notice=> 'Project was successfully created.'
    else
      redirect_to new_project_path, :alert=> 'Project was not created.'
    end
  end

  def edit
  	@project = Project.find(params[:id])
  	@client = Client.all
    @freelance = Freelance.where(:freelance_delete=>'0')
  end

  def update
    @project = Project.find(params[:id])

  	if @project.update(params.require(:project).permit(:client_id, :freelance_id, :delivery_date, :project_amount, :project_paid, :project_status, :project_details))
      redirect_to projects_path , :notice=> 'Project was successfully updated.'
    else
      redirect_to edit_projects_path, :alert=> 'Project was not updated.'
    end
  end

  def destroy
  	if @project = Project.where(:id=>params[:id]).update_all(:project_delete=>'1')
      redirect_to projects_path
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.text_field :client_id, id: :project_client_id %>
  </div>

  <div class="field">
    <%= form.label :freelance_id %>
    <%= form.text_field :freelance_id, id: :project_freelance_id %>
  </div>

  <div class="field">
    <%= form.label :delivery_date %>
    <%= form.date_select :delivery_date, id: :project_delivery_date %>
  </div>

  <div class="field">
    <%= form.label :project_amount %>
    <%= form.number_field :project_amount, id: :project_project_amount %>
  </div>

  <div class="field">
    <%= form.label :project_paid %>
    <%= form.number_field :project_paid, id: :project_project_paid %>
  </div>

  <div class="field">
    <%= form.label :project_status %>
    <%= form.text_field :project_status, id: :project_project_status %>
  </div>

  <div class="field">
    <%= form.label :project_details %>
    <%= form.text_area :project_details, id: :project_project_details %>
  </div>

  <div class="field">
    <%= form.label :project_delete %>
    <%= form.number_field :project_delete, id: :project_project_delete %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% content_for :title, "Edit Project" %>


                <!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Editar Proyecto <small>Edit Existing Proyecto Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Inicio</li>
                                <li><a class="link-effect" href="">Edit Proyecto</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="block">
                                <div class="block-header">
                                    <ul class="block-options">
                                        <li>
                                            <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                        </li>
                                        <li>
                                            <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                        </li>
                                    </ul>
                                    <h3 class="block-title">Proyecto Form <small>Requierd</small></h3>
                                </div>
                                <div class="block-content block-content-narrow">
                                    <div class="row">
                                        <div class="col-md-8 col-md-offset-2">
                                            <%= form_for @project, :html=>{:class=>'form-horizontal push-10-t'} do|f| %>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Nombre Cliente</label>
                                                    <div class="col-sm-12">
                                                        <% options = options_from_collection_for_select(@client, 'id', 'client_name', :selected => f.object.client_id) %>
                                                            <%= f.select :client_id, options, {:include_blank => false}, {:class=>'form-control select_list', :style=>"width:100%"} %>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Nombre Freelance</label>
                                                    <div class="col-sm-12">
                                                        <% options = options_from_collection_for_select(@freelance, 'id', 'freelance_name', :selected => f.object.freelance_id) %>
                                                            <%= f.select :freelance_id, options, {:include_blank => false}, {:class=>'form-control select_list', :style=>"width:100%"}  %>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Delivery Date</label>
                                                    <div class="col-sm-12">
                                                        <%= f.text_field :delivery_date, :class=>'form-control', :type=>"date", :required=>''  %>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label class="col-xs-12" for="example-password-input">Cantidad</label>
                                                            <div class="col-sm-12">
                                                                    <%= f.text_field :project_amount, :class=>'form-control', :placeholder=>"Enter Total cantidad", :type=>'number', :required=>''  %>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label class="col-xs-12" for="example-password-input">Pagado</label>
                                                            <div class="col-sm-12">
                                                                <%= f.text_field :project_paid, :class=>'form-control', :placeholder=>"Enter Pago", :type=>'number', :required=>''  %>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Detalle Proyecto</label>
                                                    <div class="col-sm-12">
                                                        <%= f.text_area :project_details, :class=>'form-control', :placeholder=>"Enter project Details", :rows=>'2', :required=>''  %>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="col-xs-12">
                                                        <div class="form-material">
                                                            <label>Estado</label>
                                                            <div class="col-xs-12">
                                                                <div class="row">
                                                                    <div class="col-md-3"><label class="css-input css-radio css-radio-default"><%= f.radio_button :project_status, 'Confirm', :class=>'icheckbox_square-green' %><span></span> Confirm </label></div>
                                                                    <div class="col-md-3"><label class="css-input css-radio css-radio-warning"><%= f.radio_button :project_status, 'Processing', :class=>'icheckbox_square-green' %><span></span> Processing </label></div>
                                                                    <div class="col-md-3"><label class="css-input css-radio css-radio-success"><%= f.radio_button :project_status, 'Ready', :class=>'icheckbox_square-green' %><span></span> Ready </label></div>
                                                                    <div class="col-md-3"><label class="css-input css-radio css-radio-primary"><%= f.radio_button :project_status, 'Delivered', :class=>'icheckbox_square-green' %><span></span> Delivered </label></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="col-sm-12">
                                                        <%= f.submit :class=>'btn btn-sm btn-primary', :value=>'submit' %>
                                                    </div>
                                                </div>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

app/views/projects/index.html.erb
                <% content_for :title, "Orders" %>


                <!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Proyecto <small>Todos los Proyectos Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Inicio</li>
                                <li><a class="link-effect" href="">Proyecto</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <!-- Dynamic Table Simple -->
                    <div class="block">
                        <div class="block-header">
                            <ul class="block-options">
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                </li>
                                <li>
                                    <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                </li>
                            </ul>
                            <h3 class="block-title">Proyecto <small>Records</small></h3>
                        </div>
                        <div class="block-content table-responsive">
                            <table class="table table-striped js-dataTable-full-pagination">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Nombre Proyecto</th>
                                        <th>Telefono</th>
                                        <th>Direccion</th>
                                        <th>Assignado a</th>
                                        <th>Cantidad</th>
                                        <th>Debe</th>
                                        <th>Fecha</th>
                                        <th>Estado</th>
                                        <th class="text-center">Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  <% @projects.each do |order|  %>
                                    <tr>
                                        <td>O-<%= project.id %></td>
                                        <td data-toggle="popover" title="Details" data-content="<%= project.project_details %>" data-placement="top"><%= project.client.client_name %></td>
                                        <td><%= project.client.client_phone %></td>
                                        <td><%= project.customer.client_address %></td>
                                        <td><%= project.freelance.freelance_name %></td>
                                        <td data-toggle="popover" title="Paid" data-content="<%= project.project_paid %>" data-placement="top"><%= project.project_amount %></td>
                                        <td><%= project.project_amount - project.project_paid %></td>
                                        <td><%= project.delivery_date %></td>
                                        <% if project.project_status == 'Confirm'  %>
                                            <td class="text-center"><span class="label label-default"> <%= project.project_status %></span></td>
                                        <% elsif project.project_status == 'Processing' %>
                                            <td class="text-center"><span class="label label-warning"> <%= project.project_status %></span></td>
                                        <% elsif project.project_status == 'Ready' %>
                                            <td class="text-center"><span class="label label-success"> <%= project.project_status %></span></td>
                                        <% elsif project.project_status == 'Delivered' %>
                                            <td class="text-center"><span class="label label-primary"> <%= project.project_status %></span></td>
                                        <% end %>
                                        <td class="text-center">
                                            <div class="btn-group">
                                                <%= link_to edit_invoice_path(project.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-plus"></i>
                                                <% end %>
                                                <%= link_to project_path(project.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-print"></i>
                                                <% end %>
                                                <%= link_to edit_project_path(project.id), :class=>'btn btn-xs btn-default' do %>
                                                    <i class="fa fa-pencil"></i>
                                                <% end %>
                                                <%= link_to project_path(project.id), :class=>'btn btn-xs btn-default', method: :delete, data: {confirm: 'Are you sure?'} do %>
                                                    <i class="fa fa-trash-o"></i>
                                                <% end %>
                                            </div>
                                        </td>
                                    </tr>
                                  <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- END Page Content -->

app/views/projects/new.html.erb
                <% content_for :title, "Add Project" %>


                <!-- Page Header -->
                <div class="content bg-gray-lighter">
                    <div class="row items-push">
                        <div class="col-sm-7">
                            <h1 class="page-heading animated zoomIn">
                                Agregar Proyecto <small>Agregar Nuevo Proyecto Data.</small>
                            </h1>
                        </div>
                        <div class="col-sm-5 text-right hidden-xs">
                            <ol class="breadcrumb push-10-t">
                                <li>Inicio</li>
                                <li><a class="link-effect" href="">Agregar Proyecto</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- END Page Header -->

                <!-- Page Content -->
                <div class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="block">
                                <div class="block-header">
                                    <ul class="block-options">
                                        <li>
                                            <button type="button" data-toggle="block-option" data-action="fullscreen_toggle"><i class="si si-size-fullscreen"></i></button>
                                        </li>
                                        <li>
                                            <button type="button" data-toggle="block-option" data-action="content_toggle"><i class="si si-arrow-up"></i></button>
                                        </li>
                                    </ul>
                                    <h3 class="block-title">Proyecto Form <small>Requierd</small></h3>
                                </div>
                                <div class="block-content block-content-narrow">
                                    <div class="row">
                                        <div class="col-md-8 col-md-offset-2">
                                            <%= form_for @project, :html=>{:class=>'form-horizontal push-10-t'} do|f| %>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Nombre Cliente</label>
                                                    <div class="col-sm-12">
                                                        <% options = options_from_collection_for_select(@client, 'id', 'client_name') %>
                                                        <%= f.select :client_id, options, {:include_blank => false}, {:class=>'form-control select_list', :style=>"width:100%"} %>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Freelance</label>
                                                    <div class="col-sm-12">
                                                        <% options = options_from_collection_for_select(@freelance, 'id', 'freelance_name') %>
                                                        <%= f.select :freelance_id, options, {:include_blank => false}, {:class=>'form-control select_list', :style=>"width:100%"}  %>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Delivery Date</label>
                                                    <div class="col-sm-12">
                                                        <%= f.text_field :delivery_date, :class=>'form-control', :type=>"date", :required=>''  %>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label class="col-xs-12" for="example-password-input">Cantidad</label>
                                                            <div class="col-sm-12">
                                                                    <%= f.text_field :project_amount, :class=>'form-control', :placeholder=>"Enter cantidad total", :type=>'number', :required=>''  %>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label class="col-xs-12" for="example-password-input">Paid</label>
                                                            <div class="col-sm-12">
                                                                <%= f.text_field :project_paid, :class=>'form-control', :placeholder=>"Enter Paid Amount", :type=>'number', :required=>''  %>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-xs-12" for="example-password-input">Detalles del Proyecto</label>
                                                    <div class="col-sm-12">
                                                        <%= f.text_area :project_details, :class=>'form-control', :placeholder=>"Enter Order Details", :rows=>'2', :required=>''  %>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="col-xs-12">
                                                        <div class="form-material">
                                                            <label>Estado</label>
                                                            <div class="col-xs-12">
                                                                <div class="row">
                                                                    <div class="col-md-3"><label class="css-input css-radio css-radio-default"><%= f.radio_button :project_status, 'Confirm', :class=>'icheckbox_square-green' %><span></span> Confirm </label></div>
                                                                    <div class="col-md-3"><label class="css-input css-radio css-radio-warning"><%= f.radio_button :project_status, 'Processing', :class=>'icheckbox_square-green' %><span></span> Processing </label></div>
                                                                    <div class="col-md-3"><label class="css-input css-radio css-radio-success"><%= f.radio_button :project_status, 'Ready', :class=>'icheckbox_square-green' %><span></span> Ready </label></div>
                                                                    <div class="col-md-3"><label class="css-input css-radio css-radio-primary"><%= f.radio_button :project_status, 'Delivered', :class=>'icheckbox_square-green' %><span></span> Delivered </label></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="col-sm-12">
                                                        <%= f.submit :class=>'btn btn-sm btn-primary', :value=>'submit' %>
                                                    </div>
                                                </div>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>