config/routes.rb
Rails.application.routes.draw do


  resources :sent_emails
  resources :credit_payments
  root :to => 'dashboards#index'
  devise_for :users
  resources :projects
  resources :salaries
  resources :freelances
  resources :invoices
  resources :clients

  resources :payments do
      collection do
        get 'enter_payment'
        put 'update_individual_payment'
        get 'filter_payments'
        get 'bulk_actions'
        get 'undo_actions'
        get 'payments_history'
        get 'invoice_payments_history'
        post 'delete_non_credit_payments'
      end
    end

    resources :invoices do
      
      collection do
        get 'filter_invoices'
        get 'bulk_actions'
        get 'undo_actions'
        post 'duplicate_invoice'
        get 'enter_single_payment'
        get 'send_invoice'
        post 'paypal_payments'
        get  'paypal_payments'
        post 'preview'
        get 'preview'
        get 'credit_card_info'
        get 'selected_currency'
      end
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :invoice
  belongs_to :client
  has_many :sent_emails, :as => :notification
  has_many :credit_payments

  def client_name
    invoice = Invoice.with_deleted.find_by_id(self.invoice_id)
    if invoice.present?
      self.unscoped_client.organization_name rescue self.client_full_name
    else
      self.unscoped_client.organization_name rescue self.client_full_name
    end
  end

  def client_full_name
    "#{self.invoice.unscoped_client.first_name rescue ''}  #{self.invoice.unscoped_client.last_name rescue ''}"
  end

  # either it's a normal payment, a credit due to overpayment or a converted payment
  def payment_reference
    self.payment_type == "credit" ? "credit-#{self.id.to_s.rjust(5, '0')}" : "#{self.invoice.invoice_number}"
  end

  def self.update_invoice_status(inv_id, c_pay, prev_amount=0)
    invoice = Invoice.find(inv_id)
    diff = (self.invoice_paid_amount(invoice.id)- prev_amount + c_pay) - invoice.invoice_total
    if diff > 0
      status = 'paid'
      self.add_credit_payment invoice, diff
      return_v = c_pay - diff
    elsif diff < 0
      status = (invoice.status == 'draft' || invoice.status == 'draft-partial') ? 'draft-partial' : 'partial'
      return_v = c_pay
    else
      status = 'paid'
      return_v = c_pay
    end
    invoice.last_invoice_status = invoice.status
    invoice.status = status
    invoice.save
    return_v
  end

  def self.update_invoice_status_credit(inv_id, c_pay)
    invoice = Invoice.find(inv_id)
    diff = (self.invoice_paid_amount(invoice.id) + c_pay) - invoice.invoice_total
    if invoice.client.present?? invoice.client.client_credit < c_pay || diff < 0 : invoice.unscoped_client.client_credit < c_pay || diff < 0
      status = (invoice.status == 'draft' || invoice.status == 'draft-partial') ? 'draft-partial' : 'partial'
      return_v = diff < 0 ? c_pay : invoice.client.client_credit
    else
      status = 'paid'
      return_v = c_pay
    end
    invoice.last_invoice_status = invoice.status
    invoice.status = status
    invoice.save
    return_v
  end

  def self.check_client_credit(invoice_id)
    invoice = Invoice.find(invoice_id)
    invoice.client.present?? invoice.client.client_credit == 0 ? true : false :  invoice.unscoped_client.client_credit == 0 ? true : false
  end

  def self.add_credit_payment(invoice, amount)
    credit_pay = Payment.new
    credit_pay.payment_type = 'credit'
    credit_pay.invoice_id = invoice.id
    credit_pay.payment_date = Date.today
    credit_pay.notes = "Overpayment against invoice# #{invoice.invoice_number}"
    credit_pay.payment_amount = amount
    credit_pay.credit_applied = 0.00
    credit_pay.company_id = invoice.company.id
    credit_pay.save
  end

  def self.invoice_remaining_amount(inv_id)
    invoice = Invoice.find(inv_id)
    invoice.invoice_total - self.invoice_paid_amount(inv_id)
  end

  def self.invoice_paid_amount(inv_id)
    invoice_payments = self.invoice_paid_detail(inv_id)
    invoice_paid_amount = 0
    invoice_payments.each do |inv_p|
      invoice_paid_amount= invoice_paid_amount + inv_p.payment_amount unless inv_p.payment_amount.blank?
    end
    invoice_paid_amount
  end

  def self.invoice_paid_detail(inv_id)
    Payment.where("invoice_id = ? and (payment_type is null || payment_type != 'credit')", inv_id).all
  end

  def self.multiple_payments(ids)
    ids = ids.split(',') if ids and ids.class == String
    where('id IN(?)', ids)
  end

  def self.delete_multiple(ids)
    multiple_payments(ids).each do |payment|
      invoice = payment.invoice

      # delete all the associations with credit payments
      payment.destroy_credit_applied(payment.id) if payment.payment_method == 'Credit'
      payment.destroy!

      # change invoice status on non credit payments deletion
      invoice.status_after_payment_deleted if invoice.present? && payment.payment_type.blank?
    end
  end

  def destroy_credit_applied(payment_id)
    CreditPayment.where('credit_id = ?', payment_id).map(&:destroy)
  end

  def notify_client current_user
    PaymentMailer.delay.payment_notification_email(current_user, self) if self.send_payment_notification
  end

  def self.payments_history(client)
    ids = client.invoices.map(&:id) #{ |invoice| invoice.id }
    where('invoice_id IN(?)', ids)
  end

  def self.payments_history_for_invoice(invoice)
    where('invoice_id = ?', invoice.id)
  end

  def self.total_payments_amount(currency=nil, company=nil)
    invoice_ids = currency.present? ? Invoice.where(currency_id: currency.id ).pluck(:id).map(&:to_s).join(",") : ""
    payment_currency_filter = (currency.present? and invoice_ids.present?) ? "invoice_id IN (#{invoice_ids})" : ""
    company_filter = company.present? ? "company_id=#{company}" : ""
    where('payment_type is null or payment_type != "credit"').where(payment_currency_filter).where(company_filter).sum('payment_amount')
  end

  def self.partial_payments(invoice_id)
    where('invoice_id = ?', invoice_id)
  end

  def self.is_credit_entry?(ids)
    CreditPayment.where('payment_id IN(?)', ids).length > 0
  end

  def self.payments_with_credit(ids)
    where('payments.id IN(?)', ids).joins(:credit_payments).group('payments.id')
  end

  def unscoped_client
    Client.unscoped.find_by_id self.client_id
  end

  
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  def index
      @payments = Payment.unarchived.page(params[:page]).per(@per_page).order(sort_column + " " + sort_direction)
      @payments = @payments.joins('LEFT JOIN invoices ON invoices.id = payments.invoice_id') if sort_column == "invoices.invoice_number"
      @payments = @payments.joins('LEFT JOIN companies ON companies.id = payments.company_id') if sort_column == "companies.company_name"
      @payments = @payments.joins('LEFT JOIN clients as payments_clients ON  payments_clients.id = payments.client_id').joins('LEFT JOIN invoices ON invoices.id = payments.invoice_id LEFT JOIN clients ON clients.id = invoices.client_id ') if sort_column == get_org_name

      #filter invoices by company
      @payments = filter_by_company(@payments)
      respond_to do |format|
        format.html # index.html.erb
        format.js
      end
    end

    def show
      @payment = Payment.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @payment }
      end
    end

    def new
      @payment = Payment.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @payment }
      end
    end

    def edit
      @payment = Payment.find(params[:id])
      if @payment.payment_method and @payment.payment_method == 'paypal'
        redirect_to payments_path,alert: "You can not edit payment with paypal!"
      end
    end

    def create
      @payment = Payment.new(payment_params)

      respond_to do |format|
        if @payment.save
          format.html { redirect_to @payment, :notice => 'The payment has been recorded successfully.' }
          format.json { render :json => @payment, :status => :created, :location => @payment }
        else
          format.html { render :action => "new" }
          format.json { render :json => @payment.errors, :status => :unprocessable_entity }
        end
      end
    end

    def update
      @payment = Payment.find(params[:id])
      latest_amount = Payment.update_invoice_status params[:payment][:invoice_id], params[:payment][:payment_amount].to_f, @payment.payment_amount.to_f
      params[:payment][:payment_amount] = latest_amount
      respond_to do |format|
        if @payment.update_attributes(payment_params)
          @payment.update_attribute(:send_payment_notification,params[:payments][0][:send_payment_notification]) if params[:payments] and params[:payments][0][:send_payment_notification]
          @payment.notify_client(current_user)  if params[:payments] and params[:payments][0][:send_payment_notification]
          format.html { redirect_to(edit_payment_url(@payment), :notice => 'Your Payment has been updated successfully.') }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @payment.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /payments/1
    # DELETE /payments/1.json
    def destroy
      @payment = Payment.find(params[:id])
      @payment.destroy

      respond_to do |format|
        format.html { redirect_to payments_url }
        format.json { head :no_content }
      end
    end

    def enter_payment
      ids = params[:invoice_ids]
      @payments = []
      ids = ids.split(",") if ids and ids.is_a?(String)
      ids.each do |inv_id|
        company_id = Invoice.find(inv_id).company_id
        @payments << Payment.new({:invoice_id => inv_id, :invoice_number =>Invoice.find(inv_id).invoice_number , :payment_date => Date.today.to_date.strftime(get_date_format), :company_id  => company_id })
      end
    end

    def update_individual_payment
      paid_invoice_ids, unpaid_invoice_ids= Services::PaymentService.update_payments(params.merge(user: current_user))
      where_to_redirect = params[:from_invoices] ? invoices_url : payments_url
      notice = ""
      alert = ""
      if paid_invoice_ids.present?
        notice =  "Payment(s) against invoice(s) with invoice # #{paid_invoice_ids.join(",")} have been recorded successfully."
      end
      if unpaid_invoice_ids.present?
        alert = "Payment(s) against invoice(s) with invoice # #{unpaid_invoice_ids.join(",")} have failed due to client's insufficiant credit balance."
      end
      redirect_to(where_to_redirect, :notice => notice , :alert => alert)
    end

    def bulk_actions
      per = params[:per].present? ? params[:per] : @per_page
      ids = params[:payment_ids]
      if Payment.is_credit_entry? ids
        @action = "credit entry"
        @payments_with_credit = Payment.payments_with_credit ids
        @non_credit_payments = ids - @payments_with_credit.collect{ |p| p.id.to_s }
      else
        Payment.delete_multiple(ids)
        @payments = Payment.unarchived.page(params[:page]).per(@per_page).order(sort_column + " " + sort_direction)
        @payments = @payments.joins('LEFT JOIN invoices ON invoices.id = payments.invoice_id') if sort_column == "invoices.invoice_number"
        @payments = @payments.joins('LEFT JOIN companies ON companies.id = payments.company_id') if sort_column == "companies.company_name"
        @payments = @payments.joins('LEFT JOIN clients as payments_clients ON  payments_clients.id = payments.client_id').joins('LEFT JOIN invoices ON invoices.id = payments.invoice_id LEFT JOIN clients ON clients.id = invoices.client_id ') if sort_column == get_org_name

        #filter invoices by company
        @payments = filter_by_company(@payments)
        @action = "deleted"
        @message = payments_deleted(ids) unless ids.blank?
      end
      respond_to { |format| format.js }
      #redirect_to payments_url
    end

    def payments_history
      client = Invoice.find_by_id(params[:id]).unscoped_client
      @payments = Payment.payments_history(client).page(params[:page]).per(@per_page)
    end

    def invoice_payments_history
      client = Invoice.find_by_id(params[:id]).unscoped_client
      invoice = Invoice.find(params[:id])
      @payments = Payment.payments_history_for_invoice(invoice).page(params[:page])
      @payments = @payments.per(@per_page)
      @invoice = Invoice.find(params[:id])
    end

    def delete_non_credit_payments
      Payment.delete_multiple(params[:non_credit_payments])
      #@payments = Payment.unarchived.page(params[:page]).per(@per_page)
      @payments = Payment.unarchived.page(params[:page]).per(@per_page).order(sort_column + " " + sort_direction)
      @payments = @payments.joins('LEFT JOIN invoices ON invoices.id = payments.invoice_id') if sort_column == "invoices.invoice_number"
      @payments = @payments.joins('LEFT JOIN companies ON companies.id = payments.company_id') if sort_column == "companies.company_name"
      @payments = @payments.joins('LEFT JOIN clients as payments_clients ON  payments_clients.id = payments.client_id').joins('LEFT JOIN invoices ON invoices.id = payments.invoice_id LEFT JOIN clients ON clients.id = invoices.client_id ') if sort_column == get_org_name
      #filter invoices by company
      @payments = filter_by_company(@payments)
      flash[:notice] = 'Payment(s) are deleted successfully'
      respond_to { |format| format.js }
    end

    private

    def set_per_page_session
      session["#{controller_name}-per_page"] = params[:per] || @per_page || 10
    end

    def sort_column
      params[:sort] ||= 'created_at'
      sort_col = params[:sort] #Payment.column_names.include?(params[:sort]) ? params[:sort] : 'clients.organization_name'
      sort_col = get_org_name if sort_col == 'clients.organization_name'
      sort_col
    end

    def sort_direction
      params[:direction] ||= 'desc'
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end

    def get_org_name
      org_name = <<-SQL
        case when payments.invoice_id is null then
          case when ifnull(payments_clients.organization_name, '') = '' then concat(payments_clients.first_name, '', payments_clients.last_name) else payments_clients.organization_name end
        else
          case when ifnull(clients.organization_name, '') = '' then concat(clients.first_name, '', clients.last_name) else clients.organization_name end
        end
      SQL
      org_name
    end

    private

    def payment_params
      params.require(:payment).permit(:client_id, :user,  :invoice_id, :notes, :paid_full, :payment_type, :payment_amount, :payment_date, :payment_method, :send_payment_notification, :archive_number, :archived_at, :deleted_at, :credit_applied, :company_id, :user)
    end
  end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :invoice_id %>
    <%= form.text_field :invoice_id, id: :payment_invoice_id %>
  </div>

  <div class="field">
    <%= form.label :payment_amount %>
    <%= form.text_field :payment_amount, id: :payment_payment_amount %>
  </div>

  <div class="field">
    <%= form.label :payment_type %>
    <%= form.text_field :payment_type, id: :payment_payment_type %>
  </div>

  <div class="field">
    <%= form.label :payment_method %>
    <%= form.text_field :payment_method, id: :payment_payment_method %>
  </div>

  <div class="field">
    <%= form.label :payment_date %>
    <%= form.date_select :payment_date, id: :payment_payment_date %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :payment_notes %>
  </div>

  <div class="field">
    <%= form.label :send_payment_notification %>
    <%= form.check_box :send_payment_notification, id: :payment_send_payment_notification %>
  </div>

  <div class="field">
    <%= form.label :paid_full %>
    <%= form.check_box :paid_full, id: :payment_paid_full %>
  </div>

  <div class="field">
    <%= form.label :archive_number %>
    <%= form.text_field :archive_number, id: :payment_archive_number %>
  </div>

  <div class="field">
    <%= form.label :credit_applied %>
    <%= form.text_field :credit_applied, id: :payment_credit_applied %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :payment_status %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.text_field :client_id, id: :payment_client_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Invoice</th>
      <th>Payment amount</th>
      <th>Payment type</th>
      <th>Payment method</th>
      <th>Payment date</th>
      <th>Notes</th>
      <th>Send payment notification</th>
      <th>Paid full</th>
      <th>Archive number</th>
      <th>Credit applied</th>
      <th>Status</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.invoice %></td>
        <td><%= payment.payment_amount %></td>
        <td><%= payment.payment_type %></td>
        <td><%= payment.payment_method %></td>
        <td><%= payment.payment_date %></td>
        <td><%= payment.notes %></td>
        <td><%= payment.send_payment_notification %></td>
        <td><%= payment.paid_full %></td>
        <td><%= payment.archive_number %></td>
        <td><%= payment.credit_applied %></td>
        <td><%= payment.status %></td>
        <td><%= payment.client %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Invoice:</strong>
  <%= @payment.invoice %>
</p>

<p>
  <strong>Payment amount:</strong>
  <%= @payment.payment_amount %>
</p>

<p>
  <strong>Payment type:</strong>
  <%= @payment.payment_type %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @payment.payment_method %>
</p>

<p>
  <strong>Payment date:</strong>
  <%= @payment.payment_date %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @payment.notes %>
</p>

<p>
  <strong>Send payment notification:</strong>
  <%= @payment.send_payment_notification %>
</p>

<p>
  <strong>Paid full:</strong>
  <%= @payment.paid_full %>
</p>

<p>
  <strong>Archive number:</strong>
  <%= @payment.archive_number %>
</p>

<p>
  <strong>Credit applied:</strong>
  <%= @payment.credit_applied %>
</p>

<p>
  <strong>Status:</strong>
  <%= @payment.status %>
</p>

<p>
  <strong>Client:</strong>
  <%= @payment.client %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>